version: "2.1"
services:
    mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        volumes:
            - ~/.vminer:/data/db
    rabbit:
        image: "rabbitmq:3-management"
        hostname: "rabbit"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
            - "5672:5672"
    grafana:
        image: "grafana/grafana"
        ports:
            - "3000:3000"
    mysql:
        image: versates/mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: vminer
            MYSQL_DATABASE: vminer
            MYSQL_USER: vminer
            MYSQL_PASSWORD: vminer
        ports:
            - "3306:3306"