#! /bin/sh
### BEGIN INIT INFO
# Provides:          mining-monitor
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mining monitor backend
### END INIT INFO

PATH=/home/inacio/.nvm/versions/node/v6.11.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
      log_begin_msg "Starting mining-monitor service"
      /var/versates/mining-monitor.sh
      log_end_msg $?
      exit 0
      ;;
  stop)
      log_begin_msg "Stopping mining-monitor unfortunately"
      curl -Is http://172.0.0.1:8100/shutdown | head -1
      log_end_msg $?
      exit 0
      ;;
  *)
      echo "Usage: /etc/init.d/mining-monitor {start|stop}"
      exit 1
      ;;
esac

